{
    "input_extension_images": "jpg",
    "output_extension_images": "jpg",
    "tile_size": 70, # tile size in pixels
    "step_size": 70, # step size in pixels for sliding window
    "input_dir_images": "/home/kalfasyan/data/Object_Detection/traffic_signs_yolo/images",
    "input_dir_annotations": "/home/kalfasyan/data/Object_Detection/traffic_signs_yolo/annotations",
    "input_format_annotations": "yolo", # yolo, pascal_voc, coco or segmentation
    "output_dir_images": "output/images",
    "output_dir_annotations": "output/annotations",
    "output_format_annotations": "yolo", # yolo or pascal_voc
    "annotation_mapping": { # mapping of annotation classes to integers
        "kernel": 0,
        "person": 1,
        "bottle": 2,
        "empty": 3,
        "trafficlight": 4,
        "speedlimit": 5,
        "crosswalk": 6,
        "stop": 7
    },
    "validate_settings": true, # validate settings before running
    "log": false, # log to file
    "log_folder": "logs", # folder to save logs
    "num_workers": -1, # number of workers for multiprocessing
    "clear_duplicates": false, # clear duplicate images in the output folder
    "draw_boxes": true, # draw bounding boxes on the output images
}
